#!/bin/bash

set -e

for lang in ar bg ca cs da de el en eo es eu fa fi fr he hu id it ja ko lt ms nl no pl pt ro ru sk sl sv tr uk vi vo zh; do
    wget --no-clobber https://dumps.wikimedia.org/${lang}wiki/latest/${lang}wiki-latest-externallinks.sql.gz
done